// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using AterraEngine.DependencyInjection;

namespace Tests.AterraEngine.DependencyInjection.Helpers;

// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
public static class CollectionHelper {
    public static IServiceCollection CreateEmptyCollection() => new ServiceCollection();
    public static IServiceCollection CreateCollectionWithServices(int count) {
        var collection = new ServiceCollection();
        ServiceHelper.AddAutoGeneratedServicesServices(collection, count);
        return collection;
    }
}
