// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using AterraEngine.DependencyInjection;

namespace Tests.AterraEngine.DependencyInjection.Helpers;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
public static class CollectionHelper {
    public static ITieredServiceCollection CreateEmptyCollection() => new TieredServiceCollection();
    public static ITieredServiceCollection CreateCollectionWithServices(int count) {
        var collection = new TieredServiceCollection();
        ServiceHelper.AddAutoGeneratedServicesServices(collection, count);
        return collection;
    }
}
