// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using AterraEngine.DependencyInjection;
using System.Diagnostics.CodeAnalysis;
using Tests.AterraEngine.DependencyInjection.Helpers;
using Tests.AterraEngine.DependencyInjection.Services;

namespace Tests.AterraEngine.DependencyInjection;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
[SuppressMessage("ReSharper", "MemberCanBeMadeStatic.Global")]
public class TieredServiceProviderTests {
    [Test]
    public async Task TieredServiceProvider_Should_Return_Service_Provider_Empty() {
        // Arrange
        var collection = new TieredServiceCollection();

        // Act
        ITieredServiceProvider provider = collection.Build();
        var container = provider.GetService<ITieredServiceContainer>();

        // Assert
        await Assert.That(container)
            .IsNotNull()
            .And.IsTypeOf<TieredServiceContainer>()
            .And.HasCount().EqualTo(0);
    }

    [Test]
    [Arguments(0b1)]
    [Arguments(0b10)]
    [Arguments(0b100)]
    [Arguments(0b1000)]
    [Arguments(0b1000_0)]
    [Arguments(0b1000_00)]
    [Arguments(0b1000_000)]
    [Arguments(0b1000_0000)]
    [Arguments(0b1000_0000_0)]
    [Arguments(0b1000_0000_00)]
    [Arguments(0b1000_0000_000)]
    [Arguments(0b1000_0000_0000)]
    // [Arguments(0b1000_0000_0000_0)] // Takes a bit too long to auto generate these services. Maybe look into a small library that can 
    // [Arguments(0b1000_0000_0000_00)]
    // [Arguments(0b1000_0000_0000_000)]
    // [Arguments(0b1000_00000_000_0000)]
    public async Task TieredServiceProvider_Should_Return_Service_Provider_Count(int count) {
        // Arrange
        var collection = new TieredServiceCollection();
        ServiceHelper.AddAutoGeneratedServicesServices(collection, count);

        // Act
        ITieredServiceProvider provider = collection.Build();
        var container = provider.GetService<ITieredServiceContainer>();


        // Assert
        await Assert.That(container)
            .IsNotNull()
            .And.IsTypeOf<TieredServiceContainer>()
            .And.HasCount().EqualTo(count);
    }

    [Test]
    [Arguments(typeof(IdService))]
    [Arguments(typeof(IIdService))]
    public async Task TieredServiceProvider_GetService_ReturnsNullOnInvalid(Type serviceType) {
        // Arrange
        var collection = new TieredServiceCollection();
        ServiceHelper.AddAutoGeneratedServicesServices(collection, 10);// THe actual count here doesn't really matter except for performance reasons.
        ITieredServiceProvider provider = collection.Build();

        // Act
        object? service = provider.GetService(serviceType);

        // Assert
        await Assert.That(service)
            .IsNull();
    }

    [Test]
    [Arguments(typeof(IIdService), typeof(IdService))]
    [Arguments(typeof(IEmptyService), typeof(EmptyService))]
    [Arguments(typeof(ITieredServiceProviderRequiredService), typeof(TieredServiceProviderRequiredService))]
    public async Task TieredServiceProvider_GetService_ReturnsValidImplementation(Type serviceType, Type implementationType) {
        // Arrange
        var collection = new TieredServiceCollection();
        ServiceHelper.AddAutoGeneratedServicesServices(collection, 10);// THe actual count here doesn't really matter except for performance reasons.
        collection.AddSingleton(serviceType, implementationType);
        ITieredServiceProvider provider = collection.Build();

        // Act
        object? service = provider.GetService(serviceType);

        // Assert
        await Assert.That(service)
            .IsNotNull()
            .And.IsAssignableTo(serviceType)
            .And.IsTypeOf(implementationType);
    }

    [Test]
    [Arguments(typeof(IdService))]
    [Arguments(typeof(IIdService))]
    public async Task TieredServiceProvider_GetRequiredService_ThrowsOnNotRegisteredService(Type serviceType) {
        // Arrange
        var collection = new TieredServiceCollection();
        ServiceHelper.AddAutoGeneratedServicesServices(collection, 10);// THe actual count here doesn't really matter except for performance reasons.
        ITieredServiceProvider provider = collection.Build();

        // Act && Assert
        await Assert.ThrowsAsync<CouldNotBeResolvedException>(() => Task.FromResult(provider.GetRequiredService(serviceType)));
    }

    [Test]
    [Arguments(typeof(IIdService), typeof(IdService))]
    [Arguments(typeof(IEmptyService), typeof(EmptyService))]
    [Arguments(typeof(ITieredServiceProviderRequiredService), typeof(TieredServiceProviderRequiredService))]
    // [Arguments(typeof(IServiceWithGenerics<,>), typeof(ServiceWithGenerics))] // TODO can only be tested when these types of generics are implemented
    public async Task TieredServiceProvider_GetRequiredService_ReturnsValidImplementation(Type serviceType, Type implementationType) {
        // Arrange
        var collection = new TieredServiceCollection();
        ServiceHelper.AddAutoGeneratedServicesServices(collection, 10);// THe actual count here doesn't really matter except for performance reasons.
        collection.AddSingleton(serviceType, implementationType);
        ITieredServiceProvider provider = collection.Build();

        // Act
        object service = provider.GetRequiredService(serviceType);

        // Assert
        await Assert.That(service)
            .IsNotNull()
            .And.IsAssignableTo(serviceType)
            .And.IsTypeOf(implementationType);
    }

    [Test]
    // ReSharper disable MethodHasAsyncOverload
    public async Task TieredServiceProvider_UsingScope_ManualDispose() {
        // Arrange
        ITieredServiceCollection collection = CollectionHelper.CreateCollectionWithServices(256);
        collection.AddScoped<IDisposableService, DisposableService>();
        ITieredServiceProvider originalProvider = collection.Build();

        var scopeProviderLevel0 = (TieredServiceProvider)originalProvider.CreateNewScope();// Cast to original type because of internal implementation.
        var scopeProviderLevel1A = (TieredServiceProvider)scopeProviderLevel0.CreateNewScope();
        var scopeProviderLevel1B = (TieredServiceProvider)scopeProviderLevel0.CreateNewScope();

        var disposableServiceDepth0 = scopeProviderLevel0.GetRequiredService<IDisposableService>();
        var disposableServiceDepth1A = scopeProviderLevel1A.GetRequiredService<IDisposableService>();
        var disposableServiceDepth1B = scopeProviderLevel1B.GetRequiredService<IDisposableService>();

        // Act
        int originalScopeCount = scopeProviderLevel0.ChildScopes.Count;
        scopeProviderLevel1A.Dispose();
        ITieredServiceProvider remainingScope = scopeProviderLevel0.ChildScopes.First();

        // Assert
        await Assert.That(originalScopeCount).IsEqualTo(2);
        await Assert.That(scopeProviderLevel0).IsNotNull();
        await Assert.That(scopeProviderLevel0.ChildScopes).HasCount().EqualTo(1);
        await Assert.That(remainingScope).IsEqualTo(scopeProviderLevel1B);

        await Assert.That(scopeProviderLevel1A.ParentScope).IsNull();
        await Assert.That(scopeProviderLevel1A.Instances).IsEmpty();
        await Assert.That(scopeProviderLevel1A.ChildScopes).IsEmpty();

        await Assert.That(disposableServiceDepth0.ConnectionString).IsNotNull();
        await Assert.That(disposableServiceDepth1A.ConnectionString).IsNull().Because("Should have been disposed");
        await Assert.That(disposableServiceDepth1B.ConnectionString).IsNotNull();
    }

    [Test]
    public async Task TieredServiceProvider_UsingScope_ManualDisposeAsync() {
        // Arrange
        ITieredServiceCollection collection = CollectionHelper.CreateCollectionWithServices(256);
        collection.AddScoped<IDisposableService, DisposableService>();
        ITieredServiceProvider originalProvider = collection.Build();
        var scopeProviderLevel0 = (TieredServiceProvider)originalProvider.CreateNewScope();// Cast to original type because of internal implementation.
        var scopeProviderLevel1A = (TieredServiceProvider)scopeProviderLevel0.CreateNewScope();
        var scopeProviderLevel1B = (TieredServiceProvider)scopeProviderLevel0.CreateNewScope();

        var disposableServiceDepth0 = scopeProviderLevel0.GetRequiredService<IDisposableService>();
        var disposableServiceDepth1A = scopeProviderLevel1A.GetRequiredService<IDisposableService>();
        var disposableServiceDepth1B = scopeProviderLevel1B.GetRequiredService<IDisposableService>();

        // Act
        int originalScopeCount = scopeProviderLevel0.ChildScopes.Count;
        await scopeProviderLevel1A.DisposeAsync();
        ITieredServiceProvider remainingScope = scopeProviderLevel0.ChildScopes.First();

        // Assert
        await Assert.That(originalScopeCount).IsEqualTo(2);
        await Assert.That(scopeProviderLevel0).IsNotNull();
        await Assert.That(scopeProviderLevel0.ChildScopes).HasCount().EqualTo(1);
        await Assert.That(remainingScope).IsEqualTo(scopeProviderLevel1B);

        await Assert.That(scopeProviderLevel1A.ParentScope).IsNull();
        await Assert.That(scopeProviderLevel1A.Instances).IsEmpty();
        await Assert.That(scopeProviderLevel1A.ChildScopes).IsEmpty();

        await Assert.That(disposableServiceDepth0.ConnectionString).IsNotNull();
        await Assert.That(disposableServiceDepth1A.ConnectionString).IsNull().Because("Should have been disposed");
        await Assert.That(disposableServiceDepth1B.ConnectionString).IsNotNull();
    }

    [Test]
    public async Task TieredServiceProvider_ShouldAllowNullableDependencies_WhenNotRegistered() {
        // Arrange
        ITieredServiceCollection collection = CollectionHelper.CreateCollectionWithServices(256);
        collection.AddTransient<INullableDependantService, NullableDependantService>();
        ITieredServiceProvider provider = collection.Build();

        // Act
        var service = provider.GetService<INullableDependantService>();

        // Assert
        await Assert.That(service).IsNotNull();
        await Assert.That(service!.Service).IsNull();
    }

    [Test]
    public async Task TieredServiceProvider_ShouldAllowNullableDependencies_WhenRegistered() {
        // Arrange
        ITieredServiceCollection collection = CollectionHelper.CreateCollectionWithServices(256);
        collection.AddTransient<INullableDependantService, NullableDependantService>();
        collection.AddTransient<IEmptyService, EmptyService>();
        ITieredServiceProvider provider = collection.Build();

        // Act
        var service = provider.GetService<INullableDependantService>();

        // Assert
        await Assert.That(service).IsNotNull();
        await Assert.That(service!.Service).IsNotNull();
    }

    [Test]
    public async Task TieredServiceProvider_ShouldUseFactoryService_WhenRegistered() {
        // Arrange
        ITieredServiceCollection collection = CollectionHelper.CreateCollectionWithServices(256);
        collection.AddSingleton<IExampleFactoryService, ExampleFactoryService>();
        collection.AddServiceFromFactory<IFactoryCreatedService, IExampleFactoryService>((int)DefaultServiceDepth.Transient);
        ITieredServiceProvider provider = collection.Build();

        // Act & Assert
        var factory = provider.GetService<IExampleFactoryService>();
        await Assert.That(factory).IsNotNull()
            .And.IsTypeOf<ExampleFactoryService>();

        for (int i = 0; i < 10; i++) {
            Guid expectedGuid = factory!.SpecificIds[i];

            var service = provider.GetService<IFactoryCreatedService>();
            await Assert.That(service).IsNotNull()
                .And.IsTypeOf<FactoryCreatedService>()
                .And.HasMember(static Guid (s) => s!.Id).EqualTo(expectedGuid)
                .Because("Should have been created by the factory which uses a set of specific ids");
        }
    }

    [Test]
    [Arguments(LifetimeSwitch.Transient)]
    [Arguments(LifetimeSwitch.Singleton)]
    [Arguments(LifetimeSwitch.Scoped)]
    public async Task TieredServiceProvider_ShouldReturn_RequiredServiceWithGenerics(LifetimeSwitch lifetimeSwitch) {
        // Arrange
        var collection = new TieredServiceCollection();
        LifetimeSwitcher.On(lifetimeSwitch,
            onTransient: () => collection.AddTransient(typeof(IServiceWithGenerics<,>), typeof(ServiceWithGenerics<,>)),
            onSingleton: () => collection.AddSingleton(typeof(IServiceWithGenerics<,>), typeof(ServiceWithGenerics<,>)),
            onScoped: () => collection.AddScoped(typeof(IServiceWithGenerics<,>), typeof(ServiceWithGenerics<,>))
        );

        ITieredServiceProvider provider = collection.Build();

        // Act 
        var service = provider.GetRequiredService<IServiceWithGenerics<string, int>>();

        // Assert
        await Assert.That(service).IsNotNull()
            .And.IsTypeOf<ServiceWithGenerics<string, int>>();
    }

    [Test]
    [Arguments(LifetimeSwitch.Transient)]
    [Arguments(LifetimeSwitch.Singleton)]
    [Arguments(LifetimeSwitch.Scoped)]
    public async Task TieredServiceProvider_ShouldReturn_RequiredServiceWithGenerics_ImplementationOnly(LifetimeSwitch lifetimeSwitch) {
        // Arrange
        var collection = new TieredServiceCollection();
        LifetimeSwitcher.On(lifetimeSwitch,
            onTransient: () => collection.AddTransient(typeof(ServiceWithGenerics<,>)),
            onSingleton: () => collection.AddSingleton(typeof(ServiceWithGenerics<,>)),
            onScoped: () => collection.AddScoped(typeof(ServiceWithGenerics<,>))
        );

        ITieredServiceProvider provider = collection.Build();

        // Act 
        var service = provider.GetService<ServiceWithGenerics<string, int>>();

        // Assert
        await Assert.That(service).IsNotNull()
            .And.IsTypeOf<ServiceWithGenerics<string, int>>();
    }

    [Test]
    public async Task TieredServiceProvider_ShouldThrow_MismatchLifetime() {
        // Arrange
        var collection = new TieredServiceCollection();
        collection.AddSingleton<ISampleService, SampleService>();
        collection.AddScoped<IEmptyService, EmptyService>();

        ITieredServiceProvider provider = collection.Build();
        
        // Act & Assert
        await Assert.ThrowsAsync<InvalidOperationException>(() => Task.FromResult(provider.GetRequiredService<ISampleService>()));
    }
    
    [Test]
    public async Task TieredServiceProvider_ShouldReturnSameInstance_WhenInstanceIsRegistered() {
        // Arrange
        var collection = new TieredServiceCollection();
        var instance = new EmptyService();
        collection.AddSingleton(instance);
        ITieredServiceProvider provider = collection.Build();

        // Act
        var service = provider.GetRequiredService<EmptyService>();

        // Assert
        await Assert.That(service.Id).IsEqualTo(instance.Id);
        await Assert.That(service).IsEqualTo(instance);
    }

    [Test]
    public async Task TieredServiceProvider_ShouldReturnEnumerableServices() {
        // Arrange
        var collection = new TieredServiceCollection();
        collection.AddEnumerableService<IEnumerableCommonInterface, EnumerableService1>((int)DefaultServiceDepth.Singleton);
        collection.AddEnumerableService<IEnumerableCommonInterface, EnumerableService2>((int)DefaultServiceDepth.Singleton);
        ITieredServiceProvider provider = collection.Build();
        
        // Act
        IEnumerableCommonInterface[] services = provider.GetRequiredService<IEnumerable<IEnumerableCommonInterface>>().ToArray();

        // Assert
        await Assert.That(services).HasCount().EqualTo(2);
        await Assert.That(services.First()).IsTypeOf<EnumerableService1>();
        await Assert.That(services.Last()).IsTypeOf<EnumerableService2>();
    }
}
