// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using CodeOfChaos.CliArgsParser;
using System.Text;

namespace Tools.AterraEngine.DependencyInjection.Commands;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
[CliArgsCommand("generate-services")]
public partial class GenerateServicesCommand : ICommand<GenerateServicesParameters> {

    public async Task ExecuteAsync(GenerateServicesParameters parameters) {
        
        Dictionary<string, string> services = GenerateServices(parameters.Count);
        string generatedCode = GenerateServiceCode(services);

        // Write to file
        string fileName = Path.Combine(Directory.GetCurrentDirectory(), parameters.Root, "tests/Tests.AterraEngine.DependencyInjection/Helpers/ServiceHelper.cs");
        await File.WriteAllTextAsync(fileName, "// Auto-generated service interface and class definitions\n" + generatedCode);
        Console.WriteLine($"\nCode has been saved to {fileName}");

    }
    private static Dictionary<string, string> GenerateServices(double count) {
        var dictionary = new Dictionary<string, string>();
        
        for (int i = 0; i < count; i++) {
            string interfaceName = $"IService{i}";
            string className = $"Service{i}";
            dictionary.Add(interfaceName, className);
        }
        
        return dictionary;
    }

    private static string GenerateServiceCode(Dictionary<string, string> services) {
        var codeBuilder = new StringBuilder();

        codeBuilder.AppendLine("// AUTOGENERATED CODE");
        codeBuilder.AppendLine();
        
        codeBuilder.AppendLine("using System;");
        codeBuilder.AppendLine("using AterraEngine.DependencyInjection;");
        
        codeBuilder.AppendLine("namespace Tests.AterraEngine.DependencyInjection.Helpers;");

        // Generate ServiceHelper class
        codeBuilder.AppendLine("""
            public static class ServiceHelper {
            
                public static IEnumerable<KeyValuePair<Type, Type>> GenerateServices(int count) => GeneratedServices.Take(count);
            
                public static IServiceCollection AddAutoGeneratedServicesServices(IServiceCollection collection, int count = 100) {
                    foreach (KeyValuePair<Type, Type> pair in GeneratedServices.Take(count)) {
                        collection.AddSingleton(pair.Key, pair.Value);
                    }
                    return collection;
                }
                
                public static Dictionary<Type, Type> GeneratedServices = new() {
            """);
        
        // Generate interfaces
        foreach ((string interfaceName, string className) in services) {
            codeBuilder.AppendLine($"        [typeof({interfaceName})] = typeof({className}),");
        }
        
        
        codeBuilder.AppendLine("    };");
        codeBuilder.AppendLine("}");
        codeBuilder.AppendLine();

        // Generate interfaces
        foreach ((string interfaceName, string className) in services) {
            codeBuilder.AppendLine($"public interface {interfaceName};");
            codeBuilder.AppendLine($"public class {className} : {interfaceName};");
        }

        return codeBuilder.ToString();

    }


}
