name: Run xUnit Tests

on:
  pull_request:
    branches:
      - core

jobs:    
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0' # Adjust the version as needed

      - name: Install dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --no-restore
        
        # Ensure that the tests must pass 
        # The job will fail automatically if any test fails because `dotnet test` exits with a non-zero code
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        